[package]
name = "HeMI"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.4"
csv = "1.1.6"
configparser = "3.0.0"
sprs = "0.11.0"
rand = "0.8.4"
either = "1.6.1"
json = "0.12.4"